### ISSUE TITLE
Defining custom lanes results in board disappearing (headers remain)

### ISSUE THREAD

**Issue by vanastassiou** [nixcloud/rt-extension-kanban#2]
Hi there,

I've just installed this extension in RT 4.4.1 and it looks like setting up custom lanes per the documentation may not work as intended. Without modifications, the Kanban module looks like Screenshot1:

![screenshot1](https://cloud.githubusercontent.com/assets/10817338/25631297/cc183068-2f24-11e7-9404-8cdd2f68b34d.jpg)

With my RT_Siteconfig.pm modifications (which include custom statuses from a custom Lifecycle) it looks like Screenshot2, even after clearing mason_data cache and restarting modperl:

![screenshot2](https://cloud.githubusercontent.com/assets/10817338/25631326/e1718978-2f24-11e7-9ecc-916e18615e6b.jpg)

Set( %KanbanConfigs, (MyFirstKanban => q(
{
  "lanes":[
    {
      "Name": "Proposed",
      "Change": {"Status": "open"},
      "Query": "(Status='new')"
    },
    {
      "Name": "In progress",
      "Change": {"Status": "resolved"},
      "Query": "(Status='in-progress')"
    }
    {
      "Name": "Blocked",
      "Change": {"Status": "resolved"},
      "Query": "(Status='blocked')"
    }
  ]
})));

The issue in Screenshot2 persists when I disable custom Lifecycles and use this:

Set( %KanbanConfigs, (MyFirstKanban => q(
{
  "lanes":[
    {
      "Name": "Proposed",
      "Change": {"Status": "new"},
      "Query": "(Status='new')"
    },
    }
  ]
}
)));

Can you provide advice? If there's a typo in my syntax, I can't see it...

Thanks.

**Comment by qknight** [comment]
we've seen that the 'websocket' status is RED, thus not connected. therefore you won't ever see life updates of the kanban. you probably know that.

paul on the other hand might have spotted a syntax error. he'll report back soon.

**Comment by seitz** [comment]
you got some syntax errors in your json code. Please check if those versions work for you:
```
Set( %KanbanConfigs, (MyFirstKanban => q({
"lanes":[
{
"Name": "Proposed",
"Change": {"Status": "open"},
"Query": "(Status='new')"
},
{
"Name": "In progress",
"Change": {"Status": "in-progress"},
"Query": "(Status='in-progress')"
},
{
"Name": "Blocked",
"Change": {"Status": "blocked"},
"Query": "(Status='blocked')"
}
]
})));
```

second one:
```
Set( %KanbanConfigs, (MyFirstKanban => q({
"lanes":[
{
"Name": "Proposed",
"Change": {"Status": "new"},
"Query": "(Status='new')"
}
]
})));
```

**Comment by vanastassiou** [comment]
That did the trick. Thanks for the help! I was going half blind trying to figure out what I did wrong.

Cheers.
